### ISSUE TITLE
External LOB option in SIARD Suite v2.1?

### ISSUE THREAD

**Issue by solfeggietto** [sfa-siard/SiardGui#1]
Is the External LOB option implemented in SIARD Suite v2.1, as this feature is described in the SIARD 2.1 format?

I have looked at both SiardGui and SiardCmd (Siard From Db), but cannot find any reference to External LOB in GUI or as parameter to console variant.

**Comment by HartwigThomas** [comment]
Yes, the external LOB option is implemented in the SiardApi. 

It is also present in SiardCmd with optional arguments -e and -m (see https://github.com/sfa-siard/SiardCmd/blob/master/doc/manual/user/usage.html). In that case only the largest LOB column is exported to the given export folder.

For more fine-grained control of LOB-Exporting you can specify a metadata.xml as an import template, which contains all desired lobfolder entries as specified by the standard.

In SiardGui the specification of a metadata.xml as an import template is not yet implemented. But the option is scheduled for the next few months.

The general procedure for exporting LOBs to external folders then is:
1. Export metadata only.
2. Edit exported metadata.xml to contain all external locations for all LOBs you may wish to export.
3. Download the database using the edited metadata.xml as a template

**Comment by solfeggietto** [comment]
Using SiardCmd with parameter -x=documents gives a resulting metadata.xml with:

Database level element <lobFolder> not present.
Column Level element <lobFolder> this single particular folder:
<lobFolder>file:///Y:/uttrekk-SiardFromDb-2.1/b20/demo/sifrdb2.1.68-mysql-to-blob01ext//documents/</lobFolder>

But when i try to use the parameter -i=metadata.xml which is the metadata file extracted above, it will not accept any <lobFolder> added in my exported metadata file, and will only extract LOB files inside the SIARD-file in the standard position.

**Comment by HartwigThomas** [comment]
The current release of SiardCmd in the "master" branch now implements corrected handling of external LOBs and its documentation describes the various options with examples.

The handling of external LOBs in SiardGui will be improved soon.
