### ISSUE TITLE
java.io.IOException: Only one column with the same name allowed per table! Joined Tabels/Views

### ISSUE THREAD

**Issue by Deathknorke** [sfa-siard/SiardGui#12]
Hey, as I already described in the other ticket, I get an IOException when archiving a view. In this view several tables are joined together.  Because of this, the column "ID" for example exists several times.

The error comes from the class "SiardApi/MetaVieImpl.java:283".
Here it is checked whether a column exists twice. 
I suspect that the table prefix has to be considered here.

Best regards

**Comment by Deathknorke** [comment]
You can use the example Database from Issue #10 .

**Comment by HartwigThomas** [comment]
The joining of several tables was never a problem. However, the idiosyncrasies of MS ACCESS SQL may present many problems in determining the columns and column types of a view.
The current release fixes a very large number of them. Please test, whether the problem persists.

Currently I am trying to determine, whether the impossibility of parsing ACCESS SQL should simply result in a message, that the view in question cannot be downloaded. That would have the advantage, that at least all table data are preserved.

The alternative is to implement a full SQL parser for MS ACCESS SQL. It is an open question, who needs this and who would finance it.

**Comment by HartwigThomas** [comment]
Please retest with current version.

**Comment by solfeggietto** [comment]
I have an example of Oracle extraction that gives the same error, though for view 
"Only one view with the same name allowed per schema!"

The database user extracts several schemas within the SID connected, so i do expect it may be 2 different schemas that both have the same view name?

Can SuardGui target specific schema(s) and not include any other schemas in the SID? Or does perhaps SiardCmd give this option?

**Comment by HartwigThomas** [comment]
If there are two schemas with the same view name, no collision should occur.
Therefore a small sample of the constellation which exhibits the problem would be welcome for bug fixing.

SiardGui targets exactly the database objects (schemas, tables, types) to which the archive user has read access (see manual). Thus the way to include/exclude schemas is to create a database user with read access to the desired selection and use it for archiving the database.

**Comment by HartwigThomas** [comment]
It is impossible to parse all MS Access query expressions, because MS Access is proprietary.
Instead, for complex queries, SIARD Suite now issues an error message in these cases, but continues the download.
So at least all primary table data and all not too complex queries are archived.
The change will be part of the next Release.
