### ISSUE TITLE
MS Access ACCDB Format: Extraction Impossible

### ISSUE THREAD

**Issue by NaumannKai** [sfa-siard/SiardGui#13]
I left an report on this on BugZilla a week ago. In short: no extracting data from ACCDB files if they contain more than tables (forms, queries, etc.).

**Comment by NaumannKai** [comment]
Thank you in advance for your kind help!!

**Comment by HartwigThomas** [comment]
Your observation is not quite true. Both table and view data CAN be extracted from ACCDB files.
However, there were quite a few bugs in the new version.

Archiving of ACCDB databases changed substantially from SIARD 1.x to SIARD 2.x.
SIARD 1.x achieved the archiving through the ODBC 32 Bit interface.

Unfortunately Microsoft changed the ODBC 64 Bit interface to an extent, that SIARD download became largely impossible.

Also, JAVA stopped supporting the JDBC/ODBC bridge from SUN.

Therefore SIARD 2.x now relies on direct access to the ACCDB data using the public domain library JACKCESS.

This has the advantage of making the download independent of the operating system:
SIARD 1.x downloads were only possible on the Windows platform with an ODBC service in place. 
SIARD 2.x "downloads" (really file conversions from ACCDB to SIARD) can now be run on any platform where JAVA is available. (Tested on Windows, Ubuntu and MacOS.)

The disadvantage of this change is, that the file format ACCDB is not open. Therefore we discover some of its quirks only through bugs being reported.

I have already fixed a number of MS Access bugs recently. I shall look into questions with the Northwind database.

**Comment by NaumannKai** [comment]
Thank you. Will try to go ahead with your advice.

**Comment by HartwigThomas** [comment]
I have fixed numerous problems with MS ACCESS views. The current release permits downloading the Nordwind database.

However, the determination of MS ACCESS view columns turns out to require full parsing of the (undocumneted!) MS ACCESS SQL. Therefore there will always be Views in the future, where the download fails.

There are two options:
- Simply display a warning with SQL which could not be parsed and continue downloading of the primary table data.
- Implement a full MS ACCESS SQL parser.
The latter costs a lot of effort. The question arises, how important it is, to have all views documented and how to fund the effort.

**Comment by NaumannKai** [comment]
Hi.

This is really good news! Thank you very much. Could you supply the URL where you accessed the Nordwind? There seem to be several versions and if I had the one you used, I would be acting safely. I will simply leave out views.

Funding is important. The Nationale Forschungsdateninfrastruktur efforts in Germany rely on making research data available, and since much data in the humanities has been stored on MS Access, there might be an option to apply for support. Contact me if you if you want to proceed into that direction.

Best regards,

Kai 

 

Von: Hartwig Thomas <notifications@github.com> 
Gesendet: Montag, 2. Dezember 2019 09:01
An: sfa-siard/SiardGui <SiardGui@noreply.github.com>
Cc: NaumannKai <kai.naumann@la-bw.de>; Author <author@noreply.github.com>
Betreff: Re: [sfa-siard/SiardGui] MS Access ACCDB Format: Extraction Impossible (#13)

 

I have fixed numerous problems with MS ACCESS views. The current release permits downloading the Nordwind database.

However, the determination of MS ACCESS view columns turns out to require full parsing of the (undocumneted!) MS ACCESS SQL. Therefore there will always be Views in the future, where the download fails.

There are two options:

*	Simply display a warning with SQL which could not be parsed and continue downloading of the primary table data.
*	Implement a full MS ACCESS SQL parser.
The latter costs a lot of effort. The question arises, how important it is, to have all views documented and how to fund the effort.

**Comment by HartwigThomas** [comment]
The download of the Nordwind database is complex. Basically MS offers a script which will create the Nordwind database adapted to your ACCESS or SQL SERVER version.
I used this one:

[Northwind.zip](https://github.com/sfa-siard/SiardGui/files/3910269/Northwind.zip)

**Comment by NaumannKai** [comment]
Great! Thanx!

 

Von: Hartwig Thomas <notifications@github.com> 
Gesendet: Montag, 2. Dezember 2019 09:52
An: sfa-siard/SiardGui <SiardGui@noreply.github.com>
Cc: NaumannKai <kai.naumann@la-bw.de>; Author <author@noreply.github.com>
Betreff: Re: [sfa-siard/SiardGui] MS Access ACCDB Format: Extraction Impossible (#13)

 

The download of the Nordwind database is complex. Basically MS offers a script which will create the Nordwind database adapted to your ACCESS or SQL SERVER version.
I used this one:

Northwind.zip <https://github.com/sfa-siard/SiardGui/files/3910269/Northwind.zip>
