### ISSUE TITLE
Debug mode is wanted to get extraction completed

### ISSUE THREAD

**Issue by solfeggietto** [sfa-siard/SiardGui#15]
A few practical examples today where Oracle 11 production base is either half completed with full dataset, almost 100% completed with metadata only or other Oracle databases some in between those  two states.

It will be apprechiated if SiardGui may have a debug-flag to be set to allow extration even if some minor or larger errors are encountered, but still produce a SIARD-package with all the tables and data that did not raise an error. A log containing what was detected of errors will also help investigate the matters.

As it is now, a large, medium or even a tiny error will cause the complete extraction to stop and no data is extracted, not even for debugging causes.

If SIardCmd have any of the option asked above please let us know.

**Comment by HartwigThomas** [comment]
We prefer to fix errors to permitting half correct archives.
There is a possibility of writing a debug log while downloading, which is described in the manual.
Whenever the metadata only could be downloaded, they can be exported as XML. Their inclusion in a bug report helps a lot.
