### ISSUE TITLE
Failed to load Database because of an IllegalArgumentException

### ISSUE THREAD

**Issue by CarlitosHa** [sfa-siard/SiardGui#16]
Hello,

I tried to load in a Microsoft Access DB and it always failed with the following error message:

> Herunterladen der Datenbank gescheitert (  java.lang.IllegalArgumentException: Column type for QUERY_BRANCHES.BRANCH could not be established!)! Unvollständiges SIARD-Archiv wird gelöscht. 

[DL link](https://we.tl/t-rSCGcNMElX) for the database in question

Thank you for your work!

**Comment by HartwigThomas** [comment]
Sorry, I was a bit too late for the download. Could you please make it the DB available to me again?

**Comment by CarlitosHa** [comment]
[Here](https://we.tl/t-e3rzDKqXn3)'s a new link.

**Comment by HartwigThomas** [comment]
Fixed in next release. (Complex MS Access queries will be skipped, but download continues.)

**Comment by CarlosHartmann** [comment]
Having another issue with this db. I can upload it again if needed and open a different issue (not sure if re-opening this one is the thing to do in this case).

After downloading the db, I get the error "Archive [path/to/siard] is invalid!" without any further information. The db works on its own so I assume the error is elsewhere.

**Comment by sfa-siard** [comment]
Hello CarlosHartmann,
I propose that you open a new issue. 
Thanks in advance.
Best regards
SFA
