### ISSUE TITLE
siardgui.jar nicht in lib enthalten

### ISSUE THREAD

**Issue by CarlitosHa** [sfa-siard/SiardGui#19]
Ich versuche SiardGui zu öffnen. Laut Anleitung in ./doc/manual/de/execution.html sollte es in ./lib/ die Datei siardgui.jar geben. Ich finde dort keine.

Wenn ich es per Kommandozeile öffnen will, bekomme ich den Fehler `Error: Unable to access jarfile lib/siardgui.jar`

Ich habe etwas herumprobiert und siardgui.cmd in ./bin/ ausgeführt, was denselben Fehler zurückgibt.

Allgemein gefragt: Ich möchte eine Access-Datenbank in Siard überführen. Soll ich das eventuell mit etwas anderem probieren oder empfehlt ihr das GUI? Ich würde gerne auch meinen KollegInnen zeigen, wie das geht. Für nicht-computeraffine Nutzer ist ein GUI aber meistens von Vorteil, denke ich.

**Comment by sfa-siard** [comment]
Hello CarlitosHa,
If you download the newest version (https://github.com/sfa-siard/SiardGui/releases/tag/2.1.34) and extract this zip, you will find the siardgui.jar under: 
.\siard_suite-2.1\lib
Best regards
SFA

**Comment by HartwigThomas** [comment]
I am not convinced, that the solution is correct. I shall check, whether the error is in the manual.

**Comment by HartwigThomas** [comment]
The code contains an Ant script which creates the binary release. 
The binary release is meant to be used as is. On Github we publish it unter "Releases".
The code is for developers who want to understand the sources or rebuild the release.
