### ISSUE TITLE
Convert MySQL zero dates to NULL by default

### ISSUE THREAD

**Issue by marhop** [sfa-siard/SiardGui#2]
Hi,

using SiardFromDb 2.1.54 (SIARD Suite 2.1.68), converting a MySQL database that contains [MySQL's dummy "zero" date value `0000-00-00`](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-types.html) fails with this error:

    java.sql.SQLException: Value '0000-00-00' can not be represented as java.sql.Date

This can be fixed on the fly by adding the `zeroDateTimeBehavior=convertToNull` option to the JDBC URL, thus converting the dummy dates to NULL. But wouldn't it be better to do this conversion by default without the need for this option?

FWIW, this error already occured with SIARD Suite 1.45, but then disappeared at least since 1.70 when the conversion was indeed done by default.

Thanks,
Martin

**Comment by HartwigThomas** [comment]
We have come to the conclusion, that the work-around with the JDBC URL is sufficient. There are cases imaginable, where people do wish to distinguish between NULL and 00.00.0000 00:00:00.
The URL documents the behavior used in the SIARD meta data. (I could imagine, however, that the default proposed for the MySQL URL already contains the option.)

**Comment by marhop** [comment]
OK, I can totally live with that. Just wondered about the default changing from SIARD Suite version to version ;-) Maybe it would, in general, be a good idea to have the SIARD Suite documentation point out and explain some common options a user might wish to add to the JDBC URL?

**Comment by HartwigThomas** [comment]
Actually there is a plan for starting a Wiki with exactly that kind of information. We will get there ...

**Comment by marhop** [comment]
Hm, on the other hand ... Won't a date value like 0000-00-00 *always* lead to a Java exception? So even if some users wanted to distinguish between 0000-00-00 and NULL, wouldn't they still end up adding the `zeroDateTimeBehavior=convertToNull` option to their JDBC URL every time because otherwise they wouldn't be able to turn their database into a SIARD file at all?

**Comment by HartwigThomas** [comment]
Yes, it will always lead to a JAVA exception. But if they have deleted the zeroDateTimeBehavior option that gives the user a chance to make a decision about how to handle zero dates, which they apparently expect not to exist. They might, instead, convert all offending cell values to something else (e.g. 01.01.0001 00:00:00), in order to preserve the difference between NULL and 00.00.0000 00:00:00. That way they also will be reminded that they have to comment the strategy chosen.
