### ISSUE TITLE
SiardGui : SQL server connection seems to only use certificates

### ISSUE THREAD

**Issue by Tarjei-stavanger** [sfa-siard/SiardGui#21]
Only using certificates is annoying since this is something that has to be added to the SQL server installation by hand after it has been installed. It is likely to involve a change process as well as several people.

For me it is highly desireable to be able to connect the same ways as DBPTK-desktop does.

**Comment by HartwigThomas** [comment]
There is nothing in the SIARD code that requires certificates.
However, the SQL Server instances may have been installed with various security features.
In SIARD one can freely configure the JDBC connection string in case the standard connection is not appropriate.
For possible connection strings, please refer to the SQL Server documentation:
https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-to-sql-server-with-the-jdbc-driver?view=sql-server-ver15

**Comment by Tarjei-stavanger** [comment]
Since I know that the SQL server instance does not have any certificate installed, I'm confident that the toolkit you are using defaults to certificate authentication. But most people would need user name/password authentication or even windows authentication. This probably requires a somewhat different invocation of the toolkit.

**Comment by mburri** [comment]
Hei @Tarjei-stavanger 

I agree with Hartwig that it should be possible to authenticate to SQL Server without any certificate - I'm never the less eager to learn more about your problem. 

Could you tell me more about your setup? 

What versions of MS SQL Server, SIARD GUI, OS are you using? 

Is there something special about your setup that we should know?

Is the SQL Server instance running locally or do you have to connect over the network?
Is it possible for you to connect to a local SQL Server?

**Comment by Tarjei-stavanger** [comment]
Have you actually tried it ?

If you have tried it with an SQL server without certificates and it worked, then it is time to look into the specifics.

I used dummy data today since it will take time to find a database to export.

![image](https://user-images.githubusercontent.com/82510602/187614486-88ba57f9-d6da-4bef-b1e3-fb5ce14a001f.png)

Notice that the JDBC URL does not include user name and password.

**Comment by mburri** [comment]
Indeed - I just succesfully tried to export a database it with a local instance ms sql server running in a docker container. 

![image](https://user-images.githubusercontent.com/4577216/187643435-e788048b-8967-4388-8ac4-bfb2c61f2eaa.png)

My connection settings are: 

![image](https://user-images.githubusercontent.com/4577216/187641533-7a60165b-8b4a-4167-b9af-2698cf3eb1dc.png)

It's actually correct that the jdbc url does not contain the username and password. What error message do you get with these settings?

By the way: we have automated tests that are running on each merge request or push to the main branch. The pipeline starts a mssql server and runs a suite of automated tests... you can look at this job that ran the last time we changed something on the main branch. https://github.com/sfa-siard/JdbcMsSql/actions/runs/2629145718 (click on the "build" job to see what it actually does)

**Comment by mburri** [comment]
But if I think about it  - we are using a standard setup - I'm not sure if there are any certificates involved. We will check that. Maybe you could nonetheless provide more information about your setup. That would be helpful for us.

**Comment by Tarjei-stavanger** [comment]
Thanks!
Knowing that it should work will be helpful for me.

**Comment by mburri** [comment]
I'm sorry - but I cannot reproduce your issue.

could you please describe: 
- your setup of your ms sql server instance (version, specific configurations regarding certificates) or point me to the relevant documentation on how your sql server is configured or how I can setup a "SQL Server without certificate"?.
- if available: error messages you got from siard gui - if any? there should be a `siard21.log` file in your temp folder where the log is written to.
- if possible: could you provide a working jdbc url connection string that you know works with your database setup?
