### ISSUE TITLE
SiardGui v2.1.87 creates empty .bin and .txt files on empty LOB fields

### ISSUE THREAD

**Issue by solfeggietto** [sfa-siard/SiardGui#3]
Siard Gui v2.1.87 have a bug on creating empty files with 0 bytes for empty LOB column rows in the table.

The Siard Suite 1.78 (Siard Edit 1.78) do NOT extract a file if the LOB element was not uploaded content file to thus being an Empty LOB row.

Tested on MySQL v5.6.35

**Comment by HartwigThomas** [comment]
I believe there is a difference between a value NULL (no LOB file) and a value '' (empty LOB file).
It is possible, that SIARD 1.x did not respect that difference correctly.
If you have an example, where SIARD does not handle these values correctly, please publish a small create table + insert statement, so the problem can be reproduced.

**Comment by HartwigThomas** [comment]
If any LOBs of a column are exported, all of them will be exported, even if their size is small.
The default maximum inline size is 4000 bytes. This is the value used by SiardCmd and SiardGui.
