### ISSUE TITLE
Loading .siard in SiardGui with javaw -jar siardgui.jar -Duser.timezone=GMT still creates timezone shift

### ISSUE THREAD

**Issue by ibbenz** [sfa-siard/SiardGui#30]
Time in Date is shifted by hours after uploading data. It does not matter if:
**javaw -jar siardgui.jar -Duser.timezone=GMT**
or
**javaw -jar siardgui.jar** 
is used.

Picture of the original Dates+Time
![Original_Time](https://user-images.githubusercontent.com/58251561/182803301-8536d9ea-c841-4748-afdb-b65b9f122013.png)

Picture of the Dates+Time after uploading it to SiardSuite
![TimeShift_AfterUpload](https://user-images.githubusercontent.com/58251561/182803309-1ffbcd51-3783-4d2f-a8ff-6d5ef5515714.png)

The .siard-file (uploaded as .zip)
[0_1-3_Northwind_simple_2022_07_10_V04.zip](https://github.com/sfa-siard/SiardGui/files/9258065/0_1-3_Northwind_simple_2022_07_10_V04.zip)

**Comment by mburri** [comment]
@ibbenz 
Thanks for your detailed report and the great finding. As always - dealing with timezones and daylight savings is quite painful...

I think the SIARD Suite uses UTC per default - If I start the application with `java -jar -Duser.timezone=UTC ./lib/siardgui.jar` the dates/ times are shown correctly.

Hope that helps - but I think we should look into this in more detail for future releases.

![image](https://user-images.githubusercontent.com/4577216/182842242-b535b960-5081-4324-8350-4db2cdaa7d19.png)

**Comment by ibbenz** [comment]
Thank you very much for your fast reply. I mixed up a bit the order of the commands.

**Comment by mburri** [comment]
You're welcome - yes, I noticed that too - the options should be placed in front of the jar file path.

**Comment by mburri** [comment]
closing this for now since the issue also depends on the users system settings - but we will have to look into this...
