### ISSUE TITLE
SIARD-->SQL-->SIARD: xs: dateTime does not correspond to recommendations of siard 2.1

### ISSUE THREAD

**Issue by ibbenz** [sfa-siard/SiardGui#47]
**Error description:**
DATE in the imported SIARD-file (table6): <c18>0001-01-01Z</c18>
DATE in the exported SIARD-file (table2)  <c18>0001-01-01</c18>

1. The DATE in table3 of the exported does not correspond to the recommendation:
   STAN_d_2018-12-04_KOST_SIARD-2.1-Format.pdf
   T_6.3-2 Recommendation: All DATES, TIMES and TIMESTAMPS should be saved with a terminating Z.

2. The xs:dateTime definition of the exported SIARD-file does not follow the example in the siard 2.1 specification, p68.
   There are "Z" lacking at the end of 0001-01-01 and 10000-01-01.
   
--> Is this a bug in Siard Suite?

**The xs:dateTime is defined as follows in the siard 2.1 specification, p68:**
xs:simpleType name="dateType">
    <xs:restriction base="xs:date">
        <xs:minInclusive value="0001-01-01Z"/>
        <xs:maxExclusive value="10000-01-01Z"/>
        <xs:pattern value="\d{4}-\d{2}-\d{2}Z?"/>
     </xs:restriction>
</xs:simpleType>

**Definition of xs:dateTime in the imported valid SIARD-file (table6.xsd)**
	<xs:simpleType name="dateType">
		<xs:restriction base="xs:date">
			<xs:minInclusive value="0001-01-01Z"/>
			<xs:maxExclusive value="10000-01-01Z"/>
			<xs:pattern value="\d{4}-\d{2}-\d{2}Z?"/>
		</xs:restriction>
	</xs:simpleType>

**Definition of xs:dateTime in the exported valid SIARD-file (table2.xsd)**
    <xs:simpleType name="dateType"> 
        <xs:restriction base="xs:date">        
            <xs:minInclusive value="0001-01-01"/>        
            <xs:maxExclusive value="10000-01-01"/>         
            <xs:pattern value="\d{4}-\d{2}-\d{2}Z?"/>       
        </xs:restriction>
    </xs:simpleType>

**siard 2.1 specification:**
[STAN_d_2018-12-04_KOST_SIARD-2.1-Format.pdf](https://github.com/sfa-siard/SiardGui/files/9682297/STAN_d_2018-12-04_KOST_SIARD-2.1-Format.pdf)

**The imported SIARD-file:**
[0_1-3_Northwind_simple_220913_B.zip](https://github.com/sfa-siard/SiardGui/files/9682566/0_1-3_Northwind_simple_220913_B.zip)

**The exported SIARD-file:**
[1.4b_1-3_Northwind_simple_220913_B.zip](https://github.com/sfa-siard/SiardGui/files/9682562/1.4b_1-3_Northwind_simple_220913_B.zip)

**Comment by ibbenz** [comment]
**1. why you reference version 2.1 of the SIARD specification?**
Our tests are executed with SiardGui 2.1.234. 
We use SiardGui 2.1 due to the fact, that we execute a comparison of three tools:
Siard Suite, dbptk and Fullconvert. 
dbptk and Fullconvert are able to create Siard 1 and Siard 2.1-files but not Siard 2.2 yet. 
Therefore, SIARD 2.1 files are used for comparison.

2. **The table2.xsd in your "imported" (?) SIARD archive does not comprise any dateType definition at all.**
It is table6.xsd which contains the dateType definition.

**3. what exactly do you mean by "exporting" a SIARD archive** 
"imported": The SIARD 1.0 archive which is uploaded with Siard Suite to the SLQ-Database              
"exported": The SIARD 2.1 archive which is downloaded from the SQL-Database using Siard Suite.
                   The downloaded data is the previously uploaded data of the SIARD 1.0 file.
 
The table number changes when the data is exported. This is the reason why the table "Employees"
corresponds to table6.xml in the "imported" SIARD 1.0 and to table2.xml in the "exported" SIARD 2.1.
          

**SIARD 2.2** 
The SIARD 2.2 specification states the same as the SIARD 2.1 specification. 
[SIARD 2.2.pdf](https://github.com/sfa-siard/SiardGui/files/9715192/SIARD.2.2.pdf)
_Dates, times and timestamps may need to be stored with terminating Z in UTC. This limitation is enforced in the definitions of dateType, timeType, and dateTimeType.
Recommendation: Store all dates, times, and timestamps with terminating Z._

On page 78 it also defines the dateType as in the SIARD 2.1-Specification.

**Comment by walkerjan** [comment]
Hello @ibbenz

Thank you very much for clarifying your issue. Luckily, the problem you report seems to affect only the specific version of SIARD Suite you are using for your test purposes. I followed your procedure using the current version (2.2.11) of SIARD Suite and found that the dateType definitions are correct (including the "Z" as required by the specification).
