### ISSUE TITLE
SIARD 2.1 --> PostgreSQL --> SIARD 2.1: no description, archiver, archiverContact -Elements after export

### ISSUE THREAD

**Issue by ibbenz** [sfa-siard/SiardGui#54]
**Issue:**
The following elements do not exist after exporting a SIARD 2.1 file from PostgreSQL with SiardSuite 2.1:
 A_M_5.1-1-3: [ERROR] : The description is mandatory inside metadata.xml dbname:(...)
 A_M_5.1-1-4: [ERROR] : The archiver is mandatory inside metadata.xml dbname:(...)
 A_M_5.1-1-5: [ERROR] : The archiverContact is mandatory inside metadata.xml dbname:(...)
The validation was done with the dbptk-Validator.

**Process:**
Upload data from 0_1-3_Northwind_simple_220913_B5_2d1.siard into a PostgreSQL database
Download the database with Siard Suite 2.1

**SIARD file which was uploaded:**
[0_1-3_Northwind_simple_220913_B5_2d1.zip](https://github.com/sfa-siard/SiardGui/files/11137694/0_1-3_Northwind_simple_220913_B5_2d1.zip)

**SIARD file which was downloaded:**
[1_3b_Northwind_simple_220913_B_2d1.zip](https://github.com/sfa-siard/SiardGui/files/11137710/1_3b_Northwind_simple_220913_B_2d1.zip)

**Comment by mburri** [comment]
These properties are not mandatory in SiardGui 2.2.11 and previous Versions.
The upcoming new implementation SiardSuite 2.2.x will address this issue.

We have yet to decide if we will backport this change.

**Comment by mburri** [comment]
Will be resolved with the new SIARD Suite 2.2.134 (https://github.com/sfa-siard/siard-suite)
