### ISSUE TITLE
SIARD 2.1 --> Microsoft SQL --> SIARD 2.1: no values for <nullable>-Elements after export

### ISSUE THREAD

**Issue by ibbenz** [sfa-siard/SiardGui#55]
**Issue:**
In metadata.xml of the imported SIARD-file there are elements <nullable>true</nullable> and <nullable>true</nullable>. After importing the data in Microsoft SQL and exporting it to SIARD 2.1 the <nullable>true</nullable> elements do not exist anymore in metadata.xml.

**Process:**
Upload data from 0_1-3_Northwind_simple_220913_B5_2d1.siard into a Microsoft SQL database.
Download the data from the database with Siard Suite 2.1 into a SIARD 2.1 file.

**SIARD file which was uploaded:**
[0_1-3_Northwind_simple_220913_B5_2d1.zip](https://github.com/sfa-siard/SiardGui/files/11137753/0_1-3_Northwind_simple_220913_B5_2d1.zip)

**SIARD file which was downloaded:**
[1_4b_Northwind_simple_220913_B_2d1.zip](https://github.com/sfa-siard/SiardGui/files/11137751/1_4b_Northwind_simple_220913_B_2d1.zip)

**Comment by sdbuehlmann** [comment]
Hi @ibbenz, thanks for your issue/request.

Actually, that's the correct behavior. If you open the downloaded SIARD file with the SIARD-Suite (or also the outdated SiardGui), you will see that the columns are still marked as nullable. The default value for the nullable flag is true. This is not so obvious in the [SIARD 2.2 spec](https://siard.dilcis.eu/SIARD%202.2/SIARD%202.2.pdf), but on page 29, you can see that nullable is an optional entry, and on page 20, you can find the note "No indication of “<nullable>” implies “<nullable>true</nullable>".
