### ISSUE TITLE
SIARD 2.1 --> Microsoft SQL --> SIARD 2.1: TIME data type: positions after decimal points disappeared

### ISSUE THREAD

**Issue by ibbenz** [sfa-siard/SiardGui#57]
**Issue:**
The numbers after the decimal point are clipped after export from a Microsoft SQL database.

Before import in Microsoft SQL Database:
 A SIARD-file has the following value in the second row in c27:
<c27>23:59:59.999999</c27>

After import: In the Microsoft SQL database: 23:59:59.999999

After export: In the exported SIARD 2.1 file
c27>23:59:59Z</c27>

**Process:**
Upload data from 0_1-3_Northwind_simple_220913_B5_2d1.siard into a Microsoft SQL database
Download the value with Siard Suite 2.1 to a SIARD 2.1 file.

**SIARD file which was uploaded:**
[0_1-3_Northwind_simple_220913_B5_2d1.zip](https://github.com/sfa-siard/SiardGui/files/11137860/0_1-3_Northwind_simple_220913_B5_2d1.zip)

**SIARD file which was downloaded:**
[1_4b_Northwind_simple_220913_B_2d1.zip](https://github.com/sfa-siard/SiardGui/files/11137852/1_4b_Northwind_simple_220913_B_2d1.zip)

**Comment by mburri** [comment]
Thanks for your issue.

We'll investigate this issue.

We will batch issues related to MS SQL in a future bugfix release.

**Comment by sdbuehlmann** [comment]
Hi @ibbenz,

I took a look into your issue:

- The SIARD standard defines no maximum resolution for the "timeType." The only information about it is that this type is a restriction of 'xs:time' to the UTC timezone. The value "23:59:59.999999" matches this and is valid.
- The maximum resolution for the TIME type for MS SQL is 100 nanoseconds (7 decimal places). The value "23:59:59.999999" also matches that limitation.
- The SIARD-Suite (and also the outdated SiardGui) works with default SQL:2008 Types. For that type, the precision is only milliseconds (3 decimal places). The value "23:59:59.999999" does not match that and will be rounded.

This means that this behavior is a limitation of SIARD-Suite but not an issue. Thank you for noticing this.
