### ISSUE TITLE
Siardgui.sh fails because bash feature is used in sh script

### ISSUE THREAD

**Issue by luis100** [sfa-siard/SiardGui#6]
https://github.com/sfa-siard/SiardGui/blob/189c7011090bcc50bcb4d40858ec56c29527a8e4/bin/siardgui.sh#L53

I fixed mine by changing /bin/sh to /bin/bash in preamble, but if could also be done in another way to be compatible with sh.

**Comment by HartwigThomas** [comment]
Thank you for the hint. I have changed all shell scripts to /bin/bash. (Almost everybody has that available nowadays.) The changes will be part of the next release.
