### ISSUE TITLE
Cannot open a SIARD 2.1 created by DBPTK

### ISSUE THREAD

**Issue by luis100** [sfa-siard/SiardGui#7]
Problem is unclear, metadata.xml validates against schema.

Error shown in command line:
`  javax.xml.bind.UnmarshalException: < org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'siardArchive'.
`

@hmiguim please add here the MySQL Sakila example.

**Comment by hmiguim** [comment]
MySQL Sakila: [mysql.zip](https://github.com/sfa-siard/SiardGui/files/3147809/mysql.zip)

**Comment by hmiguim** [comment]
Close this issue the problem no longer persists
