### ISSUE TITLE
SiardGui v2.1.105 Download error after successful Database download

### ISSUE THREAD

**Issue by solfeggietto** [sfa-siard/SiardGui#8]
SiardGui v2.1.99 and v2.1.102 works with exact same computer and database without this error.

SiardGui v2.1.105 first reports "Database was downloaded successfully" attached screenshot 1, and the SIARD-file is visible saved with the expected size (and can even be copied to a temporary folder to be examined). 

As "OK" is clicked, the dialog message "Download error | Archive " attached screenshot 2, .... path\filename.siard" is invalid!" is reported and the siard-file is deleted upon this error.

I have saved the copy of the SIARD-file before it was deleted, and it can be opened in Siard Gui v2.1.105 and is successfully passing integry check (Tool menu), attached screenshot 3.

Screenshot 1: Database was downloaded successfully
![siardgui_v2 1 105_t01testdb04int_04](https://user-images.githubusercontent.com/622856/59305132-eae0d980-8c99-11e9-86c9-2c32c5f7c608.png)

Screenshot 2: Download error (after OK clicked)
![siardgui_v2 1 105_t01testdb04int_05](https://user-images.githubusercontent.com/622856/59305173-fcc27c80-8c99-11e9-93b1-f079a670a623.png)

Screenshot 3: The copied SIARD-file preserved before clicking OK, is successful Integrity Check.
![siardgui_v2 1 105_t01testdb04int_07](https://user-images.githubusercontent.com/622856/59305484-9ee26480-8c9a-11e9-8200-866d6e981919.png)

**Comment by GregDelhauwe** [comment]
I have the same problem except that if I copy the .siard file before clicking ok, I cant open the file... Always the same "invalid"... I imagine that you open "normally" the file with the GUI in order to do the integrity check ?

**Comment by GregDelhauwe** [comment]
Also, I tried to download with the command line but same behaviour... :(

**Comment by HartwigThomas** [comment]
I still failed to be able to reproduce the issue. I would be very grateful for
- a database dump which leads to the problem, or
- a SIARD file (corrupted and uncorrupted), or at least
- an XML metadata file, which I might use to creat a database of similar stucture.

**Comment by solfeggietto** [comment]
Do you need information on Computer operating system, Java version or more?

This folder holds an Excel spreadsheet of SIARD-Interoperatbility test 2019-06-16, which shows the most important elements/differences, but also have subfolders with thes testdatabase in use produced by all the tested variants of tools and versions. It should all be open free to download from those google folders including a SiardGui v2.1.102 with success and the SiardGui v2.1.105 that failed but i managed to copy the SIARD file out before it was deleted upon the flag raised it was not successfull (the flag detection seems to be the error not the Siard extraction itself).

[SIARD-Interoperability_2019-06-14](https://drive.google.com/drive/folders/1RKKC9yx9B576C0nCfyWofMIDvb9dh-6G)

**Comment by HartwigThomas** [comment]
Thank you. That helps.

**Comment by solfeggietto** [comment]
This is the MySQL v5.6.35 we use for tests in the Uniform Server WAMP setup:

[UniformServer 13_3_2_ZeroXIII](https://sourceforge.net/projects/miniserver/files/Uniform%20Server%20ZeroXIII/13_3_2_ZeroXIII/)

**Comment by solfeggietto** [comment]
Tested SiardGui v2.1.105 with same parameters, but external LOBs. This time the SIARD-file copied (before the final OK and termination) is an invalid zip-file. SiardGiu v2.1.102 works fine creating External LOBs.

**Comment by HartwigThomas** [comment]
In the current release 2.1.108 this problem is fixed.
